name: Update Apps in Preview

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    paths:
      - 'apps/**'
    branches: 
      - preview
  workflow_dispatch: 

jobs:
    update_apps:
        runs-on: ubuntu-latest
        environment: Preview
        steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 2
            ref: preview

        - name: Install Deno
          uses: denoland/setup-deno@v1
          with:
            deno-version: v1.x

        - name: Get changed files
          id: get_changed_files
          run: echo "files=$(git diff --name-only HEAD^ | awk -F '/' '{print $NF}' | sed 's/\.json$//' | tr '\n' ' ')" >> $GITHUB_OUTPUT
          if: ${{ github.event_name == 'push' }}

        - name: Update Apps
          run: deno task update:apps ${{ steps.get_changed_files.outputs.files }}
          env:
            DENO_KV_ACCESS_TOKEN: ${{ secrets.DENO_KV_ACCESS_TOKEN }}
            DENO_KV_PATH: ${{ secrets.DENO_KV_PATH }}
