name: Update Apps

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'apps/**'
  workflow_dispatch: 

jobs:
    update_apps:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install Deno
          uses: denoland/setup-deno@v1
          with:
            deno-version: v1.x

        - name: Get changed files
          id: get_changed_files
          run: echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r HEAD | grep -v \"\.json$\" | xargs -n1 basename | tr \"\n\" \" \")"
          if: ${{ github.event_name == 'push' }}

        - name: Update Apps
          run: deno task update:apps ${{ steps.get_changed_files.outputs.files }}
          env:
            DENO_KV_TOKEN: ${{ secrets.DENO_KV_TOKEN }}
            DENO_KV_NAMESPACE: ${{ secrets.DENO_KV_NAMESPACE }}